[package]
name = "mobi"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/techwritescode/mobi-rs"

[dependencies]
anyhow = "1.0.98"
palmdoc-compression = "0.3.1"
palm_database = { path = "../palm_database" }
byyte = "0.1.0"
chrono = "0.4.41"
rand = "0.9.2"