[package]
name = "byyte"
version = "0.1.0"
edition = "2024"
description = "A library for reading and writing binary data, focusing on simplicity."
license = "MIT"
repository = "https://github.com/techwritescode/mobi-rs"

[dependencies]